[package]
name = "regolith-displayd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
calloop = "0.13"
calloop-wayland-source = "0.3"
lazy_static = "1.4.0"
log = "0.4"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
pretty_env_logger = "0.4.0"
serde = "1.0.139"
swayipc-async = "2.0.0"
tokio = { version = "1", features = ["full"] }
trawlcat = "0.2.3"
wayland-client = "=0.31.14"
wayland-protocols-wlr = { version = "=0.3.12", features = ["client"] }
zbus = { version = "2", default-features = false, features = ["tokio"] }
zvariant = "3.4.1"
